class EatClubExecutor{

	public static void main (String food[]){
		System.out.println("main started");
		double price1= EatClub.search("Biryani");
		System.out.println("the price for Biryani is " + price1);
		double price2= EatClub.search("Hummus");
		System.out.println("the price for Hummus is " + price2);
		double price3= EatClub.search("Shawarma");
		System.out.println("the price for Shawarma is " + price3);
		double price4= EatClub.search("Kebabs");
		System.out.println("the price for Kebabs is " + price4);
		double price5= EatClub.search("Falafel");
		System.out.println("the price for Falafel is " + price5);
		double price6= EatClub.search("Shawermas");
		System.out.println("the price for Shawermas is " + price6);
		double price7= EatClub.search("Couscous");
		System.out.println("the price for Couscous is " + price7);
		double price8= EatClub.search("Maqluba");
		System.out.println("the price for Maqluba is " + price8);
		double price9= EatClub.search("Harira");
		System.out.println("the price for Harira is " + price9);
		double price10= EatClub.search("Dolma");
		System.out.println("the price for Dolma is " + price10);	
		double price11= EatClub.search("Manti");
		System.out.println("the price for Manti is " + price11);	
		double price12= EatClub.search("Nasi Goreng");
		System.out.println("the price for Nasi Goreng is " + price12);	
		double price13= EatClub.search("Mandi");
		System.out.println("the price for  Mandi is " + price13);
		double price14= EatClub.search("Haleem");
		System.out.println("the price for Haleem is " + price14);
		double price15= EatClub.search("Tabouleh");
		System.out.println("the price for Tabouleh is " + price15);
		double price16= EatClub.search("Fatayer");
		System.out.println("the price for Fatayer is " + price16);
		double price17= EatClub.search("Shish Taouk");
		System.out.println("the price for Shish Taouk is " + price17);
		double price18= EatClub.search("Sambusak");
		System.out.println("the price for Sambusak is " + price18);	
		double price19= EatClub.search("Kabsa");
		System.out.println("the price for Kabsa is " + price19);	
		double price20= EatClub.search("Murtabak");
		System.out.println("the price for Murtabak is " + price20);
		double price21= EatClub.search("Tandoori Chicken");
		System.out.println("the price for Tandoori Chicken is " + price21);	
		double price22= EatClub.search("Sheer Khurma");
		System.out.println("the price for Sheer Khurma is " + price22);	
		double price23= EatClub.search("Gazpacho");
		System.out.println("the price for Gazpacho is " + price23);	
		double price24= EatClub.search("Seekh Kebabs");
		System.out.println("the price for Seekh Kebabs is " + price24);
		double price25= EatClub.search("Aloo Paratha");
		System.out.println("the price for Aloo Paratha is " + price25);
		double price26= EatClub.search("Kunafa");
		System.out.println("the price for Kunafa is " + price26);
		double price27= EatClub.search("Knafeh");
		System.out.println("the price for Knafeh is " + price27);
		double price28= EatClub.search("Jalebi");
		System.out.println("the price for Jalebi is " + price28);
		double price29= EatClub.search("Sambal");
		System.out.println("the price for Sambal is " + price29);
		double price30= EatClub.search("Lahmacun");
		System.out.println("the price for Lahmacun is " + price30);
		double price31= EatClub.search("Kibbeh");
		System.out.println("the price for Kibbeh is " + price31);
		double price32= EatClub.search("Shawerma");
		System.out.println("the price for Shawerma is " + price32);
		double price33= EatClub.search("Tahdig");
		System.out.println("the price for Tahdig is " + price33);
		double price34= EatClub.search("Adana Kebab");
		System.out.println("the price for Adana Kebab is " + price34);
		double price35= EatClub.search("Pide");
		System.out.println("the price for Pide is " + price35);
		double price36= EatClub.search("Harissa");
		System.out.println("the price for Harissa is " + price36);
		double price37= EatClub.search("Momo");
		System.out.println("the price for Momo is " + price37);
		double price38= EatClub.search("Fattoush");
		System.out.println("the price for Fattoush is " + price38);
		double price39= EatClub.search("Pastilla");
		System.out.println("the price for Pastilla is " + price39);
		double price40= EatClub.search("Tabbouleh");
		System.out.println("the price for Tabbouleh is " + price40);
		double price41= EatClub.search("Ghormeh Sabzi");
		System.out.println("the price for Ghormeh Sabzi is " + price41);
		double price42= EatClub.search("Ful Medames");
		System.out.println("the price for Ful Medames is " + price42);
		double price43= EatClub.search("Mandazi");
		System.out.println("the price for Mandazi is " + price43);
		double price44= EatClub.search("Shorba");
		System.out.println("the price for Shorba is " + price44);
		double price45= EatClub.search("Roti Canai");
		System.out.println("the price for Roti Canai is " + price45);
		double price46= EatClub.search("Salmon Roe Fish Tacos");
		System.out.println("the price for Salmon Roe Fish Tacos is " + price46);
		double price47= EatClub.search("Thieboudienne");
		System.out.println("the price for Thieboudienne is " + price47);
		double price48= EatClub.search("Kunun Gyada");
		System.out.println("the price for Kunun Gyada is " + price48);
		double price49= EatClub.search("Sabzi Polo");
		System.out.println("the price for Sabzi Polo is " + price49);
		double price50= EatClub.search("Nihari");
		System.out.println("the price for Nihari is " + price50);
		System.out.println("main ended");
		
		}
		}