class EatSureExecutor{

	public static void main (String food[]){
		System.out.println("main started");
		double price1= EatSure.search("malabar parotta");
		System.out.println("the price for malabar parotta is " + price1);
		double price2= EatSure.search("Plum Cake");
		System.out.println("the price for Plum Cake is " + price2);
		double price3= EatSure.search("Vegetable Stew");
		System.out.println("the price for Vegetable Stew is " + price3);
		double price4= EatSure.search("Beetroot Thoran");
		System.out.println("the price for Beetroot Thoran is " + price4);
		double price5= EatSure.search("Aval Laddu");
		System.out.println("the price for Aval Laddu is " + price5);
		double price6= EatSure.search("Mushroom Pepper Fry");
		System.out.println("the price for Mushroom Pepper Fry is " + price6);
		double price7= EatSure.search("Curd Rice");
		System.out.println("the price for Curd Rice is " + price7);
		double price8= EatSure.search("Cabbage Thoran");
		System.out.println("the price for Cabbage Thoran is " + price8);
		double price9= EatSure.search("Avial ");
		System.out.println("the price for Avial  is " + price9);
		double price10= EatSure.search("Kadala Curry");
		System.out.println("the price for Kadala Curry is " + price10);	
		double price11= EatSure.search("Star Gooseberry Pickle");
		System.out.println("the price for Star Gooseberry Pickle is " + price11);	
		double price12= EatSure.search("Mathanga Erissery");
		System.out.println("the price for Mathanga Erissery is " + price12);	
		double price13= EatSure.search("Kozhukattai");
		System.out.println("the price for Kozhukattai is " + price13);
		double price14= EatSure.search("Malabar Biryani");
		System.out.println("the price for Malabar Biryani is " + price14);
		double price15= EatSure.search("Yam Chips");
		System.out.println("the price for Yam Chips is " + price15);
		double price16= EatSure.search("Onam Sadhya");
		System.out.println("the price for Onam Sadhya is " + price16);
		double price17= EatSure.search("Beans Thoran");
		System.out.println("the price for Beans Thoran is " + price17);
		double price18= EatSure.search("Jackfruit Payasam");
		System.out.println("the price for Jackfruit Payasam is " + price18);	
		double price19= EatSure.search("Pineapple Pachadi");
		System.out.println("the price for Pineapple Pachadi is " + price19);	
		double price20= EatSure.search("Naranga Achar");
		System.out.println("the price for Naranga Achar is " + price20);
		double price21= EatSure.search("Kuska Rice");
		System.out.println("the price for Kuska Rice is " + price21);	
		double price22= EatSure.search("Kappa Puzhukku");
		System.out.println("the price for Kappa Puzhukku is " + price22);	
		double price23= EatSure.search("Majjiga");
		System.out.println("the price for Majjiga is " + price23);	
		double price24= EatSure.search("Peking chi");
		System.out.println("the price for Peking chi is " + price24);
		double price25= EatSure.search("Satay");
		System.out.println("the price for Satay is " + price25);
		double price26= EatSure.search("Shawarma");
		System.out.println("the price for  Shawarma is " + price26);
		double price27= EatSure.search("risotto");
		System.out.println("the price for risotto is " + price27);
		double price28= EatSure.search("palav");
		System.out.println("the price for palav is " + price28);
		double price29= EatSure.search("egg burji");
		System.out.println("the price for egg burji is " + price29);
		double price30= EatSure.search("rotti");
		System.out.println("the price for rotti is " + price30);
		double price31= EatSure.search("lemon rice");
		System.out.println("the price for lemon rice is " + price31);
		double price32= EatSure.search("samosa");
		System.out.println("the price for samosa is " + price32);
		double price33= EatSure.search("kaima balls");
		System.out.println("the price for kaima balls is " + price33);
		double price34= EatSure.search("mutton sambar");
		System.out.println("the price for mutton sambar is " + price34);
		double price35= EatSure.search("fried rice");
		System.out.println("the price for fried rice is " + price35);
		double price36= EatSure.search("french fries");
		System.out.println("the price for french fries is " + price36);
		double price37= EatSure.search("skinless kabab");
		System.out.println("the price for skinless kabab is " + price37);
		double price38= EatSure.search("kurma");
		System.out.println("the price for kurma is " + price38);
		double price39= EatSure.search("gee rice");
		System.out.println("the price for gee rice is " + price39);
		double price40= EatSure.search("potato dal");
		System.out.println("the price for potato dal is " + price40);
		double price41= EatSure.search("poori");
		System.out.println("the price for poori is " + price41);
		double price42= EatSure.search("salad");
		System.out.println("the price for salad is " + price42);
		double price43= EatSure.search("bread toast");
		System.out.println("the price for bread toast is " + price43);
		double price44= EatSure.search("chicken Leg fry");
		System.out.println("the price for chicken Leg fry is " + price44);
		double price45= EatSure.search("Lamb Kebabs");
		System.out.println("the price for Lamb Kebabs is " + price45);
		double price46= EatSure.search("Fish Tacos");
		System.out.println("the price for Fish Tacos is " + price46);
		double price47= EatSure.search("bath");
		System.out.println("the price for bath is " + price47);
		double price48= EatSure.search("chicken Leg Fritters");
		System.out.println("the price for chicken Leg Fritters is " + price48);
		double price49= EatSure.search("Teriyaki Beef");
		System.out.println("the price for Teriyaki Beef is " + price49);
		double price50= EatSure.search("Sardine Salad");
		System.out.println("the price for Sardine Salad is " + price50);
		System.out.println("main ended");
		
		}
		}