class SwiggyExecutorone{

	public static void main (String food[]){
		
		System.out.println("main started");
		double price= Swiggyone.search("pizza");
		System.out.println("the price for pizza is " +price);
		double price1= Swiggyone.search("burger");
		System.out.println("the price for burger is " +price1 );
		double price2= Swiggyone.search("sushi");
		System.out.println("the price for sushi is " +price2 );
		double price3= Swiggyone.search("pav bhaji");
		System.out.println("the price for pav bhaji is " +price3 );	
		double price4= Swiggyone.search("bhel puri");
		System.out.println("the price for bhel puri is " +price4);
		double price5= Swiggyone.search("aloo tikki");
		System.out.println("the price for aloo tikki is " +price5 );
		double price6= Swiggyone.search("litti chokha"); 
		System.out.println("the price for litti chokha is " +price6 );//clss name.methodname();
		double price7= Swiggyone.search("momo");
		System.out.println("the price for momo is " +price7 );
		double price8= Swiggyone.search("puchka");
		System.out.println("the price for puchka is " +price8 );
		double price9= Swiggyone.search("papdi chaat");
		System.out.println("the price for papdi chaat is " +price9 );		//condition expression  == relational oper
		double price10= Swiggyone.search("poha jalebi");
		System.out.println("the price for poha jalebi is " +price10 );
		double price11= Swiggyone.search("vada pav");
		System.out.println("the price for vada pav is " +price11);
		double price12= Swiggyone.search("khasta kachori");
		System.out.println("the price for khasta kachori is " +price12 );
		double price13= Swiggyone.search("dabeli");
		System.out.println("the price for dabeli is " +price13 );
		double price14= Swiggyone.search("idli");
		System.out.println("the price for idli is " +price14 );
		double price15= Swiggyone.search("uttapam");
		System.out.println("the price for uttapam is " +price15);
		double price16= Swiggyone.search("rasam");
		System.out.println("the price for rasam is " +price16 );
		double price17= Swiggyone.search("gulab jamun");
		System.out.println("the price for gulab jamun is " +price17 );
		double price18= Swiggyone.search("appam");
		System.out.println("the price for appam is " +price18 );
		double price19= Swiggyone.search("chapati");
		System.out.println("the price for chapati is " +price19 );
		double price20= Swiggyone.search("batata vada");
		System.out.println("the price for batata vada is " +price20 );
		double price21= Swiggyone.search("rajma chawal");
		System.out.println("the price for rajma chawal is " +price21);
		double price22= Swiggyone.search("Kulfi falooda");
		System.out.println("the price for Kulfi falooda is " +price22 );
		double price23= Swiggyone.search("Paneer makhani");
		System.out.println("the price for Paneer makhani is " +price23 );
		double price24= Swiggyone.search("parotta");
		System.out.println("the price for parotta is " +price24 );
		double price25= Swiggyone.search("chilli paneer");
		System.out.println("the price for chilli paneer is " +price25 );
		double price26= Swiggyone.search("medu vada");
		System.out.println("the price for medu vada is " +price26 );
		double price27= Swiggyone.search("barfi");
		System.out.println("the price for barfi is " +price27 );
		double price28= Swiggyone.search("mango chutney");
		System.out.println("the price for mango chutney is " +price28);
		double price29= Swiggyone.search("nihari");
		System.out.println("the price for nihari is " +price29 );
		double price30= Swiggyone.search("dal makhani");
		System.out.println("the price for dal makhani is " +price30);
		double price31= Swiggyone.search("sambar");
		System.out.println("the price for sambar is " +price31 );
		double price32= Swiggyone.search("pulihora");
		System.out.println("the price for pulihora is " +price32 );
		double price33= Swiggyone.search("kheer");
		System.out.println("the price for kheer is " +price33 );
		double price34= Swiggyone.search("pulao");
		System.out.println("the price for pulao is " +price34 );
		double price35= Swiggyone.search("kashmiri naan");
		System.out.println("the price for kashmiri naan is " +price35 );
		double price36= Swiggyone.search("mattar paneer");
		System.out.println("the price for mattar paneer is " +price36 );
		double price37= Swiggyone.search("rajma");
		System.out.println("the price for rajma is " +price37);
		double price38= Swiggyone.search("coconut chutney");
		System.out.println("the price for coconut chutney is " +price38 );
		double price39= Swiggyone.search("aloo gobi");
		System.out.println("the price for aloo gobi is " +price39 );
		double price40= Swiggyone.search("laddu");
		System.out.println("the price for laddu is " +price40 );
		double price41= Swiggyone.search("palak paneer");
		System.out.println("the price for palak paneer is " +price41);
		double price42= Swiggyone.search("pakoda");
		System.out.println("the price for pakoda is " +price42 );
		double price43= Swiggyone.search("papadum");
		System.out.println("the price for papadum is " +price43 );
		double price44= Swiggyone.search("chana masala");
		System.out.println("the price for chana masala is " +price44);
		double price45= Swiggyone.search("aamras");
		System.out.println("the price for aamras is " +price45);
		double price46= Swiggyone.search("rumali roti");
		System.out.println("the price for rumali roti is " +price46);
		double price47= Swiggyone.search("dessert");
		System.out.println("the price for dessert is " +price47);
		double price48= Swiggyone.search("misal");
		System.out.println("the price for misal is " +price48);
		double price49= Swiggyone.search("raita");
		System.out.println("the price for raita is " +price49 );
		System.out.println("main ended");
		
		}
		}
		