class SwiggyExecutorone{

	public static double main (String food[]){
		System.out.println("main started");
		Swiggy1.search("pizza");
		System.out.println("the price for pizza is " );
		Swiggy1.search("burger");
		System.out.println("the price for burger is " );
		Swiggy1.search("sushi");
		System.out.println("the price for sushi is " );
		Swiggy1.search("pav bhaji");
		System.out.println("the price for pav bhaji is " );	
		Swiggy1.search("bhel puri");
		System.out.println("the price for bhel puri is " );
		Swiggy1.search("aloo tikki");
		System.out.println("the price for aloo tikki is " );
		Swiggy1.search("litti chokha"); 
		System.out.println("the price for litti chokha is " );//clss name.methodname();
		Swiggy1.search("momo");
		System.out.println("the price for momo is " );
		Swiggy1.search("puchka");
		System.out.println("the price for puchka is " );
		Swiggy1.search("papdi chaat");
		System.out.println("the price for papdi chaat is " );		//condition expression  == relational oper
		Swiggy1.search("poha jalebi");
		System.out.println("the price for poha jalebi is " );
		Swiggy1.search("vada pav");
		System.out.println("the price for vada pav is 15");
		Swiggy1.search("khasta kachori");
		System.out.println("the price for khasta kachori is " );
		Swiggy1.search("dabeli");
		System.out.println("the price for dabeli is " );
		Swiggy1.search("idli");
		System.out.println("the price for idli is " );
		Swiggy1.search("uttapam");
		System.out.println("the price for uttapam is " );
		Swiggy1.search("rasam");
		System.out.println("the price for rasam is " );
		Swiggy1.search("gulab jamun");
		System.out.println("the price for gulab jamun is " );
		Swiggy1.search("appam");
		System.out.println("the price for appam is " );
		Swiggy1.search("chapati");
		System.out.println("the price for chapati is " );
		Swiggy1.search("batata vada");
		System.out.println("the price for batata vada is " );
		Swiggy1.search("rajma chawal");
		System.out.println("the price for rajma chawal is " );
		Swiggy1.search("Kulfi falooda");
		System.out.println("the price for Kulfi falooda is " );
		Swiggy1.search("Paneer makhani");
		System.out.println("the price for Paneer makhani is " );
		Swiggy1.search("parotta");
		System.out.println("the price for parotta is " );
		Swiggy1.search("chilli paneer");
		System.out.println("the price for chilli paneer is " );
		Swiggy1.search("medu vada");
		System.out.println("the price for medu vada is " );
		Swiggy1.search("barfi");
		System.out.println("the price for barfi is " );
		Swiggy1.search("mango chutney");
		System.out.println("the price for mango chutney is " );
		Swiggy1.search("nihari");
		System.out.println("the price for nihari is " );
		Swiggy1.search("dal makhani");
		System.out.println("the price for dal makhani is " );
		Swiggy1.search("sambar");
		System.out.println("the price for sambar is " );
		Swiggy1.search("pulihora");
		System.out.println("the price for pulihora is " );
		Swiggy1.search("kheer");
		System.out.println("the price for kheer is " );
		Swiggy1.search("pulao");
		System.out.println("the price for pulao is " );
		Swiggy1.search("kashmiri naan");
		System.out.println("the price for kashmiri naan is " );
		Swiggy1.search("mattar paneer");
		System.out.println("the price for mattar paneer is " );
		Swiggy1.search("rajma");
		System.out.println("the price for rajma is " );
		Swiggy1.search("coconut chutney");
		System.out.println("the price for coconut chutney is " );
		Swiggy1.search("aloo gobi");
		System.out.println("the price for aloo gobi is " );
		Swiggy1.search("laddu");
		System.out.println("the price for laddu is " );
		Swiggy1.search("palak paneer");
		System.out.println("the price for palak paneer is " );
		Swiggy1.search("pakoda");
		System.out.println("the price for pakoda is " );
		Swiggy1.search("papadum");
		System.out.println("the price for papadum is " );
		Swiggy1.search("chana masala");
		System.out.println("the price for chana masala is " );
		Swiggy1.search("aamras");
		System.out.println("the price for aamras is " );
		Swiggy1.search("rumali roti");
		System.out.println("the price for rumali roti is " );
		Swiggy1.search("dessert");
		System.out.println("the price for dessert is " );
		Swiggy1.search("misal");
		System.out.println("the price for misal is ");
		Swiggy1.search("raita");
		System.out.println("the price for raita is " );
		System.out.println("main ended");
		
		}
		}
		