class UberEatsExecutor{

	public static void main (String food[]){
		System.out.println("main started");
		double price1= UberEats.search("Hyderabad biryani");
		System.out.println("the price for Hyderabad biryani is " + price1);
		double price2= UberEats.search("Rogan Josh");
		System.out.println("the price for Rogan Josh is " + price2);
		double price3= UberEats.search("Dhokla");
		System.out.println("the price for Dhokla is " + price3);
		double price4= UberEats.search("Chole Bhature");
		System.out.println("the price for Chole Bhature is " + price4);
		double price5= UberEats.search("Masala Dosa");
		System.out.println("the price for Masala Dosa is " + price5);
		double price6= UberEats.search("Golgappa");
		System.out.println("the price for Golgappa is " + price6);
		double price7= UberEats.search("Misal Pav");
		System.out.println("the price for Misal Pav is " + price7);
		double price8= UberEats.search("Aloo Paratha");
		System.out.println("the price for Aloo Paratha is " + price8);
		double price9= UberEats.search("Vada Pav");
		System.out.println("the price for Vada Pav is " + price9);
		double price10= UberEats.search("soup");
		System.out.println("the price for soup is " + price10);	
		double price11= UberEats.search("Hyderabadi Haleem");
		System.out.println("the price for Hyderabadi Haleem is " + price11);	
		double price12= UberEats.search("Litti Chokha");
		System.out.println("the price for Litti Chokha is " + price12);	
		double price13= UberEats.search("Rajma Chawal");
		System.out.println("the price for Rajma Chawal is " + price13);
		double price14= UberEats.search("Malai Kofta");
		System.out.println("the price for Malai Kofta is " + price14);
		double price15= UberEats.search("Kashmiri Pulao");
		System.out.println("the price for Kashmiri Pulao is " + price15);
		double price16= UberEats.search("Pesarattu Upma");
		System.out.println("the price for Pesarattu Upma is " + price16);
		double price17= UberEats.search("Jalebi");
		System.out.println("the price for Jalebi is " + price17);
		double price18= UberEats.search("Dhansak");
		System.out.println("the price for Dhansak is " + price18);	
		double price19= UberEats.search("Rosogolla");
		System.out.println("the price for Rosogolla is " + price19);	
		double price20= UberEats.search("Maacher Jhol");
		System.out.println("the price for Maacher Jhol is " + price20);
		double price21= UberEats.search("Poha");
		System.out.println("the price for Poha is " + price21);	
		double price22= UberEats.search("Thepla");
		System.out.println("the price for Thepla is " + price22);	
		double price23= UberEats.search("Appam with Stew");
		System.out.println("the price for Appam with Stew is " + price23);	
		double price24= UberEats.search("Pork Vindaloo");
		System.out.println("the price for Pork Vindaloo is " + price24);
		double price25= UberEats.search("Patra");
		System.out.println("the price for Patra is " + price25);
		double price26= UberEats.search("Keema Pav");
		System.out.println("the price for Keema Pav is " + price26);
		double price27= UberEats.search("Dum Aloo");
		System.out.println("the price for Dum Aloo is " + price27);
		double price28= UberEats.search("Galouti Kebab");
		System.out.println("the price for Galouti Kebab is " + price28);
		double price29= UberEats.search("Mysore Pak");
		System.out.println("the price for Mysore Pak is " + price29);
		double price30= UberEats.search("cream based soup");
		System.out.println("the price for cream based soup is " + price30);
		double price31= UberEats.search("Paneer Tikka");
		System.out.println("the price for Paneer Tikka is " + price31);
		double price32= UberEats.search("Aloo Dum");
		System.out.println("the price for Aloo Dum is " + price32);
		double price33= UberEats.search("Chhena Poda");
		System.out.println("the price for Chhena Poda is " + price33);
		double price34= UberEats.search("Tangy Chutneys");
		System.out.println("the price for Tangy Chutneys is " + price34);
		double price35= UberEats.search("Kalaadi");
		System.out.println("the price for Kalaadi is " + price35);
		double price36= UberEats.search("Khar");
		System.out.println("the price for Khar is " + price36);
		double price37= UberEats.search("Bhut Jolokia Curry");
		System.out.println("the price for Bhut Jolokia Curry is " + price37);
		double price38= UberEats.search("Kachori");
		System.out.println("the price for Kachori is " + price38);
		double price39= UberEats.search("Sol Kadhi");
		System.out.println("the price for Sol Kadhi is " + price39);
		double price40= UberEats.search("Sattu Paratha");
		System.out.println("the price for Sattu Paratha is " + price40);
		double price41= UberEats.search("Bamboo Shoot Curry");
		System.out.println("the price for Bamboo Shoot Curry is " + price41);
		double price42= UberEats.search("Lai Pata");
		System.out.println("the price for Lai Pata is " + price42);
		double price43= UberEats.search("Modak");
		System.out.println("the price for Modak is " + price43);
		double price44= UberEats.search("Alleppey Fish Curry");
		System.out.println("the price for Alleppey Fish Curry is " + price44);
		double price45= UberEats.search("Gundruk");
		System.out.println("the price for Gundruk is " + price45);
		double price46= UberEats.search("Salmon Roe Fish Tacos");
		System.out.println("the price for Salmon Roe Fish Tacos is " + price46);
		double price47= UberEats.search("Shrimp Po' Boy");
		System.out.println("the price for Shrimp Po' Boy is " + price47);
		double price48= UberEats.search("Baingan Bharta");
		System.out.println("the price for Baingan Bharta is " + price48);
		double price49= UberEats.search("butter bun maska");
		System.out.println("the price for butter bun maska is" + price49);
		double price50= UberEats.search("Lavang Latika");
		System.out.println("the price for Lavang Latika is " + price50);
		System.out.println("main ended");
		
		}
		}