class ZomatoExecutor{

	public static void main (String food[]){
		System.out.println("main started");
		double price= Zomato.search("Chicken Tikka");
		System.out.println("the price for Chicken Tikka is " + price);
		price= Zomato.search("Beef Burger");
		System.out.println("the price for Beef Burger is " + price);
		price= Zomato.search("Fish Tacos");
		System.out.println("the price for Fish Tacos is " + price);
		price= Zomato.search("Pork Chops");
		System.out.println("the price for Pork Chops is " + price);
		price= Zomato.search("Lamb Curry");
		System.out.println("the price for Lamb Curry is " + price);
		price= Zomato.search("Shrimp Scampi");
		System.out.println("the price for Shrimp Scampi is " + price);
		price= Zomato.search("Bacon and Eggs");
		System.out.println("the price for Bacon and Eggs is " + price);
		 price= Zomato.search("Sausage Chicken Tikka");
		System.out.println("the price for Sausage Chicken Tikka is " + price);
		 price= Zomato.search("Lobster Bisque");
		System.out.println("the price for Lobster Bisque is " + price);
		 price= Zomato.search("Turkey Sandwich");
		System.out.println("the price for Turkey Sandwich is " + price);	
		 price= Zomato.search("Duck Confit");
		System.out.println("the price for Duck Confit is " + price);	
		 price= Zomato.search("Venison Stew");
		System.out.println("the price for Venison Stew is " + price);	
		 price= Zomato.search("Clam Chowder");
		System.out.println("the price for Clam Chowder is " + price);
		 price= Zomato.search("Cakes");
		System.out.println("the price for Cakes is " + price);
		 price= Zomato.search("Meatball Sub");
		System.out.println("the price for Meatball Sub is " + price);
		 price= Zomato.search("Grilled Salmon");
		System.out.println("the price for Grilled Salmon is " + price);
		 price= Zomato.search("Oyster Rockefeller");
		System.out.println("the price for Oyster Rockefeller is " + price);
		 price= Zomato.search("Bison Steak");
		System.out.println("the price for Bison Steak is " + price);	
		 price= Zomato.search("Roast chicken");
		System.out.println("the price for Roast chicken is " + price);	
		 price= Zomato.search("chicken chilli");
		System.out.println("the price for chicken chilli is " + price);
		 price= Zomato.search("Tandoori Chicken");
		System.out.println("the price for Tandoori Chicken is " + price);	
		 price= Zomato.search("Fried Catfish");
		System.out.println("the price for Fried Catfish is " + price);	
		 price= Zomato.search("Spicy Sausages");
		System.out.println("the price for Spicy Sausages is " + price);	
		 price= Zomato.search("Peking chicken");
		System.out.println("the price for Peking chicken is " + price);
		 price= Zomato.search("Chicken Satay");
		System.out.println("the price for Chicken Satay is " + price);
		 price= Zomato.search("Chicken Shawarma");
		System.out.println("the price for Chicken Shawarma is " + price);
		 price= Zomato.search("risotto");
		System.out.println("the price for risotto is " + price);
		 price= Zomato.search("apple pie");
		System.out.println("the price for apple pie is " + price);
		 price= Zomato.search("whole roasted fish");
		System.out.println("the price for whole roasted fish is " + price);
		 price= Zomato.search("cream based soup");
		System.out.println("the price for cream based soup is " + price);
		 price= Zomato.search("butter chicken");
		System.out.println("the price for butter chicken is " + price);
		 price= Zomato.search("samosa");
		System.out.println("the price for samosa is " + price);
		 price= Zomato.search("lassi");
		System.out.println("the price for lassi is " + price);
		 price= Zomato.search("dosa");
		System.out.println("the price for dosa is " + price);
		 price= Zomato.search("fried rice");
		System.out.println("the price for fried rice is " + price);
		 price= Zomato.search("french fries");
		System.out.println("the price for french fries is " + price);
		 price= Zomato.search("boneless wings");
		System.out.println("the price for boneless wings is " + price);
		 price= Zomato.search("pad thai");
		System.out.println("the price for pad thai is " + price);
		 price= Zomato.search("ice cream");
		System.out.println("the price for ice cream is " + price);
		 price= Zomato.search("potato chips");
		System.out.println("the price for potato chips is " + price);
		 price= Zomato.search("soft drinks");
		System.out.println("the price for soft drinks is " + price);
		 price= Zomato.search("salad");
		System.out.println("the price for salad is " + price);
		 price= Zomato.search("toast");
		System.out.println("the price for toast is " + price);
		 price= Zomato.search("chicken Legs");
		System.out.println("the price for chicken Legs is " + price);
		 price= Zomato.search("Lamb Kebabs");
		System.out.println("the price for Lamb Kebabs is " + price);
		 price= Zomato.search("Salmon Roe Fish Tacos");
		System.out.println("the price for Salmon Roe Fish Tacos is " + price);
		 price= Zomato.search("Shrimp Po' Boy");
		System.out.println("the price for Shrimp Po' Boy is " + price);
		 price= Zomato.search("chicken Leg Fritters");
		System.out.println("the price for chicken Leg Fritters is " + price);
		 price= Zomato.search("Teriyaki Beef");
		System.out.println("the price for Teriyaki Beef is " + price);
		 price= Zomato.search("Sardine Salad");
		System.out.println("the price for Sardine Salad is " + price);
		System.out.println("main ended");
		
		}
		}